### ISSUE TITLE
support for scaladoc generation

### ISSUE THREAD

**Issue by softprops** [bazelbuild/rules_scala#256] opened 2017-08-02 18:36 UTC
Not sure if this has come up in the past but I think it's useful to have on the issue tracker if not. It would nice to have an entry point for generating scaladocs, if even in some tar package format. Relevant upstream issue can be found [here](https://github.com/bazelbuild/bazel/issues/446)

**Comment by pauldraper** [comment] 2018-09-07 04:27
Duplicate of #230

**Closed** 2018-09-07 04:35 UTC

**Comment by johnynek** [comment] 2019-05-31 16:51
@softprops this is done now!
