### ISSUE TITLE
support neverlink in scala_library

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#213] opened 2017-06-02 18:47 UTC
java rules support this, but we don't.

**Comment by sdtwigg** [comment] 2017-06-02 18:56
This seems pretty straightforward to implement (just involves a little fiddling with setting up the jar lists in the provider). There might be a little incongruence with java interop until can safely use the new bazel CLs.

Do you know how to test it?

**Comment by ittaiz** [comment] 2017-06-02 20:30
Stephen,
Wdyt about sending a PR where the only blocker is that it uses bazel from
head?
Will enable to start flushing out problems.

**Comment by softprops** [comment] 2017-06-02 20:52
What is neverlink?

**Comment by sdtwigg** [comment] 2017-06-02 21:32
https://bazel.build/versions/master/docs/be/java.html#java_library.neverlink

Basically, when included, the jar is added to the compile path of dependents but not the runtime path or dependents (direct or transitive).

@ittaiz yes, a situation using neverlink just hasn't come up for me yet so would be aided by advice on testing it. (I suppose I could fake it by creating a neverlink target (with stub implementation) and then a similar target identical one (same interface, real implementation) that is included as a runtime_dep?)

**Comment by ittaiz** [comment] 2017-06-03 04:19
The problem with testing neverlink is that the problem we're trying to
solve in the lead target is potential and order based on the classpath. If
the leaf will have the "correct" "linked" version first then there
shouldn't be a problem.
I have an idea which isn't very pretty but should work- have two targets
with different names implement the same interface (can be same
implementation) and assert in the test that only one of them is in the
classpath.
The downside to this test is that it doesn't demonstrate why it's a problem
but because the problem is tricky to reproduce (the order of loading the
jars) I think it's ok alongside a comment.

**Comment by kien-truong** [comment] 2019-12-10 11:47
Do we have any progress on this ? It'd be very useful to strip down jars of Spark jobs.

**Comment by smparkes** [comment] 2019-12-10 16:37
FWIW, we had the spark use case and were able to get unblocked by using `deploy_env`:

https://docs.bazel.build/versions/master/be/java.html#java_binary.deploy_env
https://github.com/bazelbuild/rules_scala/issues/576

**Comment by kien-truong** [comment] 2019-12-11 02:05
Thanks for the tips. We've also succeeded in using `deploy_env` to strip out Spark's class.

**Comment by TheKaur** [comment] 2020-10-19 03:18
@ittaiz Are we going to support neverlink for scala_library?

**Comment by ittaiz** [comment] 2020-10-19 03:38
We can.
I think we haven't because no one cared enough to add it.

**Comment by TheKaur** [comment] 2020-10-19 04:00
@ittaiz Is there someone who can help implement it? I am not at all versed with bazel code but can give it a shot if no one is available

**Comment by ittaiz** [comment] 2020-10-19 05:15
@blorente @liucijus ?

**Comment by liucijus** [comment] 2020-10-19 13:46
I will look into it

**Comment by liucijus** [comment] 2021-01-28 05:29
Fixed by #1123

**Closed by liucijus** 2021-01-28 05:29 UTC
