### ISSUE TITLE
New version of Intellij Plugin breaks debug capability

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/rules_scala#866] opened 2019-10-31 20:02 UTC
## Problem
This commit: https://github.com/bazelbuild/intellij/commit/5f03bde0f02f5d1693a4567dc129230420a30372 released with versions newer than `2019.08.19.0.6` of the intellij plugin breaks Intellj's capability to run a debugger. I believe the reason is that the commit uses the new `Provider` syntax where I believe rules_scala is still using the old version.

Reference: https://github.com/bazelbuild/intellij/issues/1281

**Comment by ittaiz** [comment] 2019-10-31 21:01
rules_scala passes both JavaInfo and a legacy struct.
IJ plugin moved some time ago to take scala data from JavaInfo but reverted it due to a bug in Bazel (released only in 1.1.0)
The commit you link to changes the aspect which is a local file you can edit.
You can remove the “scala” specific conditional and so the aspect will take the data from the JavaInfo we expose.
Can you try and edit it to see if it solves the issue?

**Comment by KaoruDev** [comment] 2019-10-31 21:02
sure, could you please point me to where I can edit the aspect file?

**Comment by ittaiz** [comment] 2019-11-01 07:39
Yes. 
In your `Bazel console` pane you should see two flags passed to Bazel.
`--aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect={some_dir}`
You should edit `intellij_info_bundled.bzl` under `some_dir` and manually revert
https://github.com/bazelbuild/intellij/commit/b3436863e08baffcd2803f430fef75e7e14849f0

**Comment by ittaiz** [comment] 2019-11-04 16:14
@KaoruDev any updates? Also please make sure to use bazel 1.1.0 when you test

**Comment by KaoruDev** [comment] 2019-11-04 16:15
sorry @ittaiz it's been a busy week personally and at work 😭I'll try to get to this by EOW

**Comment by KaoruDev** [comment] 2019-11-04 20:09
@ittaiz Ok I changed `intellij_info_impl.bzl` file to:

```
def get_java_provider(target):
    """Find a provider exposing java compilation/outputs data."""

    if JavaInfo in target:
        return target[JavaInfo]

    # Check for scala and kt providers before JavaInfo. e.g. scala targets have
    # JavaInfo, but their data lives in the "scala" provider and not JavaInfo.
    # See https://github.com/bazelbuild/intellij/pull/1202
    if hasattr(target, "scala"):
        return target.scala
    if hasattr(target, "kt") and hasattr(target.kt, "outputs"):
        return target.kt
    return None
```

still getting:

```
Traceback (most recent call last):
	File "/Users/kaoru/code/learning_bazel/person/BUILD", line 10
		@intellij_aspect//:java_classpath.bzl%java_classpath_aspect(...)
	File "/private/var/tmp/_bazel_kaoru/<sha>/external/intellij_aspect/java_classpath.bzl", line 16, in _runtime_classpath_impl
		struct(<1 more arguments>)
	File "/private/var/tmp/_bazel_kaoru/<sha>/external/intellij_aspect/java_classpath.bzl", line 17, in struct
		_get_runtime_jars(target)
	File "/private/var/tmp/_bazel_kaoru/<sha>/external/intellij_aspect/java_classpath.bzl", line 22, in _get_runtime_jars
		target[JavaInfo].compilation_info.runtime_classpath
object of type 'NoneType' has no field 'runtime_classpath'
```

**Comment by ittaiz** [comment] 2019-11-05 04:36
Strange...
Good thing I also know my way around the plugin so I’ll debug it.
Please note it will take me a few days to get to it since I’m super swamped
with a big PR in rules_scala and a few work stuff

**Comment by ittaiz** [comment] 2019-11-05 08:45
@KaoruDev three questions:
1. The commit you originally linked to is [stale](https://github.com/bazelbuild/intellij/commit/b3436863e08baffcd2803f430fef75e7e14849f0) for a round a month and a half and it seems there have been two releases with the revert  v2019.10.28 v2019.10.14. You didn't use any of these versions, right? Maybe that would have solved it?
2. Have you checked with Bazel 1.0.0 or 1.1.0?
3. When you write

> still getting:
Are you sure this is what you got originally? Maybe this is a new issue?

**Comment by ittaiz** [comment] 2019-11-05 09:12
Re 3- I saw that in the other issue it’s indeed there so I see.

Most important for me is to understand if you’re seeing this on an up to date plugin version? I think we found this issue and handled it already.

If I’m correct the issue is actually in Bazel in the starlark JavaInfo constructor (which explain why google doesn’t see it since they use the native JavaInfo constructor)

**Comment by ittaiz** [comment] 2019-11-05 12:30
ok, from my investigation the issue is indeed in Bazel/IntelliJ integration and not rules_scala related.
Additionally it doesn't exist in latest plugin but will become a blocker in Bazel 3.0 since they plan to remove the struct return option and use providers solely but the provider here is broken.
https://github.com/bazelbuild/bazel/issues/10170

**Comment by ittaiz** [comment] 2019-11-05 12:47
closing since it seems it's an IJ issue and a Bazel issue.
Please reopen if you disagree or have new info.

**Closed by ittaiz** 2019-11-05 12:47 UTC
