### ISSUE TITLE
README instructions not working with current HEAD

### ISSUE THREAD

**Issue by dgarzon** [bazelbuild/rules_scala#726] opened 2019-04-03 20:13 UTC
Hi, I am trying to update to the latest version of `rules_scala`, but am running into: 
```
external/io_bazel_rules_scala/scala/scala.bzl:501:5: no such package '@com_google_protobuf//': The repository could not be resolved and referenced by '//external:io_bazel_rules_scala/dependency/com_google_protobuf/protobuf_java'
```

I was able to trace the issue to the following commit: `3393c52c8fa0f7e2c7d57f19f27087ebc41bdef2`. All other commits before that one work with current instructions in the `README.md`. Can someone please provide guidance on how to get the latest version working? Thanks in advanced!

**Comment by beala-stripe** [comment] 2019-04-03 20:19
To get you unblocked, you can add the dependency yourself to your WORKSPACE file:

https://github.com/bazelbuild/rules_scala/blob/499df53b38f66ace84d8c426f3b5d8a338a4798f/WORKSPACE#L94-L99

**Comment by beala-stripe** [comment] 2019-04-03 20:23
@johnynek Is this change intentional? If so, I'd be happy to add it to the README. It seems that this was caused by this change: https://github.com/bazelbuild/rules_scala/pull/709/files#diff-9957b181001dad28e385437a86e99126L481 Should the protobuf dep be pulled in by `scala_repositories`?

**Comment by dgarzon** [comment] 2019-04-03 20:29
Thanks for the prompt response @beala-stripe, but unfortunately I am now running into a compilation error, it seems:

```
ERROR: /private/var/tmp/_bazel_danielgarzon/e7640762bd2c7e4bec47cd7778dbc4d4/external/com_google_protobuf/BUILD:69:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 37 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_google_protobuf/src/google/protobuf/io/zero_copy_stream.cc:35:
external/com_google_protobuf/src/google/protobuf/io/zero_copy_stream.h:110:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
```

**Comment by beala-stripe** [comment] 2019-04-03 20:39
The bazel C++ toolchain isn't very hermetic and sometimes issues like this that can be caused by a bad cache entry. Can you try `bazel clean --expunge` and try again?

**Comment by dgarzon** [comment] 2019-04-03 20:47
After doing so, I get a similar error:
```
ERROR: /private/var/tmp/_bazel_danielgarzon/e7640762bd2c7e4bec47cd7778dbc4d4/external/com_google_protobuf/BUILD:259:1: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 37 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_google_protobuf/src/google/protobuf/compiler/subprocess.cc:33:
In file included from external/com_google_protobuf/src/google/protobuf/compiler/subprocess.h:43:
external/com_google_protobuf/src/google/protobuf/stubs/common.h:38:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 error generated.
```

**Comment by dgarzon** [comment] 2019-04-03 21:34
I was able to get a bit further, but I don't understand why using `rules_scala` needs to build `protobuf` from scratch. Is this intentional?

**Comment by johnynek** [comment] 2019-04-03 22:22
I merged the PR but didn’t write it. The change was to use the google proto repo protoc tool instead of the one in a jar.

I don’t know why bazel is building that if you don’t use proto though. That seems strange.

As to whether it should be in scala_repositories, I think we should try to make it only needed by people using protobuf ideally. But maybe a short term fix is to put the dependency in the function.

**Comment by johnynek** [comment] 2019-04-03 22:25
oh, I guess the issues is this:

https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L503

we should guard that bind with something like:
https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L493

I think the problem is we always have that bind now, even if you don't use proto... so, maybe that is the fix?

**Comment by beala-stripe** [comment] 2019-04-04 19:57
It looks like quite a few things depend on protobufs (ie, not just the scalapb/protobufs toolchain):

```
$ bazel query 'allpaths(//..., external//io_bazel_rules_scala/dependency/com_google_protobuf/protobuf_java) intersect //...'
//third_party/unused_dependency_checker/src/test:unused_dependency_checker_test
//third_party/unused_dependency_checker/src/main:unused_dependency_checker
//third_party/dependency_analyzer/src/test:dependency_analyzer_test
//third_party/utils/src/test:test_util
//third_party/dependency_analyzer/src/main:dependency_analyzer
//src/scala/scripts:scalapb_generator
//src/scala/scripts:scalapb_generator_lib
//src/scala/scripts:scala_proto_request_extractor
//src/scala/scripts:generator
//src/scala/scripts:generator_lib
//src/scala/io/bazel/rules_scala/tut_support:tut_compiler
//src/scala/io/bazel/rules_scala/tut_support:tut_compiler_lib
//src/scala/io/bazel/rules_scala/scrooge_support:compiler
//src/scala/io/bazel/rules_scala/scrooge_support:focused_zip_importer
//src/scala/io/bazel/rules_scala/jmh_support:benchmark_generator
//src/scala/io/bazel/rules_scala/jmh_support:benchmark_generator_lib
//src/java/io/bazel/rulesscala/worker:worker
//src/java/io/bazel/rulesscala/specs2:specs2_test_discovery
//src/java/io/bazel/rulesscala/test_discovery:test_discovery
//src/java/io/bazel/rulesscala/scalac:scalac
//src/java/io/bazel/rulesscala/coverage/instrumenter:instrumenter
//src/java/com/google/devtools/build/lib:worker
//scala_proto:enable_all_options_toolchain_impl
//scala_proto:default_toolchain_impl
//scala/support:test_reporter
```

To me that suggests it should probably be brought in by `scala_repositories`, similar to how `@com_google_protobuf//:protobuf_java` used to be brought in by `scala_repositories`. WDYT?

**Comment by johnynek** [comment] 2019-04-04 21:13
yep. Seems like we need to fix it then.

**Comment by dgarzon** [comment] 2019-04-05 01:02
Hi @beala-stripe and @johnynek thanks for taking a look. One concern I have is that it is now building Protobuf from scratch. Seems like a lot of overhead to me. Any way we can pull the binary instead?

**Comment by johnynek** [comment] 2019-04-05 01:17
it should be cached (although when your C++ toolchain changes, you will need to recompile).

I'd love to see any PRs which can make it faster without sacrificing reproducibility/caching which improve performance.

**Comment by pboutes** [comment] 2019-04-11 02:23
Heya, 
until this issue is resolved, you can pull the jar dependency, and basically recreate the jar file with the correct structure by creating the missing `protobuf_java` target. This is faster, and avoids building Protobuf from scratch.
Is this workaround elegant? Mehhh 😆

```python
PROTOBUF_JAVA_VERSION = "3.6.1"

http_archive(
    name = "com_google_protobuf",
    url = "http://central.maven.org/maven2/com/google/protobuf/protobuf-java/%s/protobuf-java-%s.jar" % (PROTOBUF_JAVA_VERSION, PROTOBUF_JAVA_VERSION),
    sha256 = "fb66d913ff0578553b2e28a3338cbbbe2657e6cfe0e98d939f23aea219daf508",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "meta",
    srcs = glob([
        "META-INF/**/*",
    ])
)

filegroup(
    name = "classes",
    srcs = glob([
        "com/**/*",
        "google/**/*",
    ])
)

genrule(
    name = "protobuf_java",
    srcs = [":meta", ":classes"],
    outs = ["myjar.jar"],
    toolchains = ["@bazel_tools//tools/jdk:current_java_runtime"],
    cmd = "mkdir -p META-INF && mkdir -p com/google/protobuf && mv $(locations :meta) META-INF && mv $(locations :classes) com/google/protobuf && $(JAVABASE)/bin/jar cfM $@ META-INF com",
)
    """,
)
```

**Comment by thundergolfer** [comment] 2019-09-04 01:11
Note that the above hack from @pboutes does work but on `HEAD` as of today you will also need to make sure `zlib` is available as `rules_scala` won't be able to get it after the hack has mangled `@ com_google_protobuf`. 

We did: 

```
http_archive(
    name = "zlib",
    build_file = "@bazel_tools//third_party/zlib:BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = ["https://zlib.net/zlib-1.2.11.tar.gz"],
)
```

Which solves at least that problem.

**Comment by chenrui333** [comment] 2021-01-12 17:12
@thundergolfer Thanks for the sharing, it helps solve my issue.

```
/home/runner/.cache/bazel/_bazel_runner/11ea874bde9302d81a91edf58f0892dc/external/com_google_protobuf/BUILD.bazel:16:8: in cmd attribute of genrule rule @com_google_protobuf//:protobuf_java: label '@com_google_protobuf//:meta' in $(locations) expression expands to no files
```

**Comment by liucijus** [comment] 2021-03-03 06:36
I assume the problem was fixed, please reopen if it's not a case

**Closed by liucijus** 2021-03-03 06:36 UTC
