### ISSUE TITLE
don't depend on all of bazel to get the worker API

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_scala#119] opened 2017-01-09 17:30 UTC
The worker API uses protobufs that are housed in the bazel repo. As a result, to build that worker process we need to pull all of bazel.

We should either copy the protobufs and build our own client, or copy the generated java code and build that.

**Comment by ittaiz** [comment] 2017-01-09 17:32
Just today I suffered from this on a slow connection after not building
rules_scala for a long time :)

**Comment by ittaiz** [comment] 2017-01-09 21:34
isn't this duplicate of #116 ?

**Comment by johnynek** [comment] 2017-01-09 21:54
yes. @ittaiz thanks! Forgot.

**Closed** 2017-01-09 21:54 UTC
