### ISSUE TITLE
No support for building deploy jars in scala

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_scala#25] opened 2016-04-06 13:18 UTC
See bazelbuild/bazel#468

**Comment by jcoveney** [comment] 2016-04-18 21:44
It's unclear to me from that ticket what work is remaining to be done on the rules_scala side...care to elaborate?

**Comment by johnynek** [comment] 2016-04-19 20:10
i think this is a duplicate of #20

**Closed by johnynek** 2016-04-19 20:10 UTC
Labels: duplicate
