### ISSUE TITLE
broken upgrade process with mixed java/scala projects

### ISSUE THREAD

**Issue by softprops** [bazelbuild/rules_scala#619] opened 2018-09-26 02:28 UTC
I'm upgrading the the latest  bazel + latest rules_scala and believe I've found a or have unknowingly been depending on a behavior that's since been deemed a bug and since removed support wise

I'll try to outline my case below

We currently have a scala library rule which previously depended on a source jar containing generated java sources, some paths to individual java sources, with dependencies on a scala library ( using mixed java/scala ) and a java import which was essentially an alias to a collection of vendored jars.

```python
scala_library(
    name = "label-foo",
    srcs = [":source-jar-containing-java"] + [
        "src/main/java/com/path/to/Foo.java"
    ],
    javacopts = JAVAC_OPTS_NO_WARN,
    scalac_jvm_flags = JVM_FLAGS,
    deps = [
        "//scala-library-label",
        "//java-import-label",
    ],
)
```

when inspecting the `bazel-bin/{package}/{label-foo}.jar` with `unzip -l` I was surprised to find only a manifest file with no class files. I hypothesized that maybe there was a change that required at least some scala files so I though in a dummy scala source into the `srcs`attr list and rerun the ùnzip -l`to my suprise the only class file listed was for the scala source. Did something change where you can no longer provide java sources as srcs for scala_library rules? My next step is doing to see if I can finagle bazel a bit to make this a java_library but am not sure if I can then have a scala_library as a dependency.

This is kind of time sensitive.  If this was a known change and there's a commit I can point to just before that commit, that'd work as well.

**Comment by johnynek** [comment] 2018-09-26 02:43
We have tests for mixed targets, but they generate a separate output. We delegate to bazel's java support and let it compile the java, then we emit multiple jars in those cases.

How are you depending on this target? Can you repro with a test?

https://github.com/bazelbuild/rules_scala/blob/master/scala/private/rule_impls.bzl#L434

It should be named with `_java.jar`:
https://github.com/bazelbuild/rules_scala/blob/master/scala/private/rule_impls.bzl#L330

**Comment by softprops** [comment] 2018-09-26 02:43
update porting this to a `java_library` was as simple as removing the `scalac_jvm_flags` options. its new to me that java rules can now depend on scala libraries. However this seemed to generate slightly different class files as what once compiled no longer compiles. 

aside also seeing a number of these types of errors

```
DEBUG: .../external/io_bazel_rules_scala/scala/private/common.bzl:51:7: ignored dependency, has no JavaInfo: <target @meetuplib//:org_spire_math_spire_macros>
```

I can't immediately recall by the scala macros in spire needed to be placed in a filegroup in the past. This seems now to be an error as a input for scala rules

```
filegroup(
    name = "org_spire_math_spire_macros",
    srcs = ["xxx/spire-macros_2.11-0.9.0.jar"],
    visibility = ["//visibility:public"],
)
```

**Comment by softprops** [comment] 2018-09-26 02:50
> How are you depending on this target?

It is a little complicated in this case. The output of the scala_rule was depended on as a java which was consumed by in internal rule we have which outputs another jar out. That jar was included as in the `deps` list of another `scala_library`. I think that's illegal now because of the JavaInfo requirement.

there's a [comment in the scala rules code about using java_import](https://github.com/bazelbuild/rules_scala/blob/958864711b3fe00045ac57b2ba86f709eeb8262d/scala/private/common.bzl#L66-L67) so im now re-exporting the jar ouput via java_import as an indirection to satisfy the scala rules

```python
# this allows me to depend on the jar output
java_import(
    name = "foo-label",
    jars = [":previous-foo-label"]
)
```

**Comment by softprops** [comment] 2018-09-26 02:53
It'd take some time to whittle down a test case I can post here but for now I'll post what I learn

**Comment by softprops** [comment] 2018-09-26 03:02
I think the difference in compiled classes with java_library and scala_library had to do with some generic type parameter variance. 

a short but hopefully not too abstract example is an error that came out of a scala_library rule that depends on the ( now ) java_library mentioned above

```
 found   : com.foo.ClassThatExtendsGuavaFunctionMentionedBelow
 required: com.google.common.base.Function[com.foo.In,com.bar.Out]
      .fetch[Out](In.methodThatReturnsClassThatExtendsGuavaFunctionMentionedBelow)
```

when previously ran though scala_library, the classfiles generated supported subclasses of guava functions as valid inputs to this generic function. when ran through java_library, the classfiles generated seem to not support subclasses of guava functions.

**Comment by johnynek** [comment] 2018-09-26 03:09
you need to use `scala_import` for those kinds of targets now.

Java has been able to depend on scala rules output for a while.

I don't see why our changes could give static errors like that. We still pass the java code to the scala compiler, we just invoke javac differently.

**Comment by johnynek** [comment] 2018-09-26 03:10
https://github.com/bazelbuild/rules_scala/blob/master/scala/scala_import.bzl#L119

there is the scala_import rule.

**Comment by softprops** [comment] 2018-09-26 03:37
I think in many of these cases I was depending a bit too much on impl details and perhaps the older way scala rules interfaces with javac. Thanks for your help and quick responses on these @johnynek

**Comment by johnynek** [comment] 2018-09-26 03:41
The good news is the internal details are more abstracted and there are more contracts now (JavaInfo provider, for instance).

Hopefully, you won't see another painful upgrade.

**Comment by softprops** [comment] 2018-09-26 14:03
I'll try bumping don't to 0.15.2 for now

**Comment by softprops** [comment] 2018-09-26 15:01
error prone still seems active with bazel 0.15.2 but this may save my some other surprises of compiling for java 9 and running on java 8

**Comment by ittaiz** [comment] 2018-09-26 15:10
that is the one I was referring to. Error prone is active since we moved to using java rules under the hood (which was many months ago).
To use java 8 on 16 and above you need:
--java_toolchain --host_java_toolchain use `bootclasspath = ["@bazel_tools//tools/jdk:platformclasspath8.jar"],` and `source_version = "8", target_version = "8",`
 --host_javabase --javabase point to a java_runtime of jdk 8
You should be able to find more details on the bazel issue tracker

**Comment by softprops** [comment] 2018-09-26 15:13
thanks @ittaiz this is very helpful. we're going to try to make a smaller leap that's still a leap from 0.6.1 to 0.15.2 for now. It may be worth mentioning some of this on your readme, or linking to the bazel docs for java on how these rules interact with java. This seems very notable for many companies. On a positive note, this is giving us a good kick in the pants. We should really be thinking about moving to java 9 anyway. Java 10 and 11 are already on the way!

**Comment by ittaiz** [comment] 2018-09-26 15:39
I know, the docs on this are bazel related and are unfortunately in
somewhat of a disarray.
Btw, java 11 was released a few days ago.
Though Bazel isn't 11 ready.

**Comment by softprops** [comment] 2018-09-26 16:13
that's kind of my indicator of how far behind we are :)

**Comment by softprops** [comment] 2018-09-27 00:04
did anything interesting change with scala test integration with scala_test rules

I got our build working but now I'm hitting an running error .


```
*** RUN ABORTED *** (1 second, 568 milliseconds)
  java.lang.IncompatibleClassChangeError: Found interface org.scalacheck.Test$Parameters, but class was expected
  at org.scalatest.prop.Configuration$class.getParams(Configuration.scala:444)
  at com.meetup.base.statsd.StatsTest.getParams(StatsTest.scala:15)
  at org.scalatest.prop.GeneratorDrivenPropertyChecks$class.forAll(GeneratorDrivenPropertyChecks.scala:1135)
  at com.meetup.base.statsd.StatsTest.forAll(StatsTest.scala:15)
```

this is likely do to a version the scalacheck we have on our classpath, scalacheck_2.11-1.11.5.jar but I wanted to check so that I could line up versions

**Comment by softprops** [comment] 2018-09-27 00:09
spotted. I think we'd previously been depending on https://mvnrepository.com/artifact/org.scalatest/scalatest_2.11/2.2.0 which has an optional dependency on scalacheck 1.11.3.  

the new version in scala rules https://mvnrepository.com/artifact/org.scalatest/scalatest_2.12/3.0.5 has an optional dependency on 1.13.5. fun

I've got some test dep version upgrades to sort though :)

**Comment by softprops** [comment] 2018-09-27 01:41
Quick heads up. The version of scala test scala rules is pinned ( [3.0.5](https://github.com/bazelbuild/rules_scala/blob/2676400bed17b03fdd0fe13a8794eb0ff0129284/scala/scala.bzl#L309-L310) ) to may be problematic for those using scalatest's scalacheck integration -- https://github.com/scalatest/scalatest/issues/1012#issuecomment-424925878 

This is more of an open issue for scalatest but given the current circumstances what are the options over overriding the scalatest version scala rules uses. It seems some of the folks affected but this have had more luck with scalatest@3.0.0 + scalacheck@1.13.4  https://github.com/scalatest/scalatest/issues/1012#issuecomment-261385950

**Comment by johnynek** [comment] 2018-09-27 03:10
you can select your own versions of those dependencies by implementing your own:

https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L278

or by setting up a bind to:
`io_bazel_rules_scala/dependency/scalatest/scalatest`

it would be nice for this to be easier to configure.

**Comment by softprops** [comment] 2018-09-27 04:05
Ohhh that's interesting so this wires up to native maven jars. I can see I'd have to somehow rebind to this name https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L333. At the end of the day in a day in the life of a bazel build, everything is just a label anyway. So I could try that.

 An alternate approach I was thinking which we're kind of already doing was using a named java_imports for test deps like Scalacheck ( we just have ivy vendor jars in local gitignored dirs so we can share between sbt/bazel ) and just add that label in the scala_test rules list of deps. What I'm unsure about there is how to opt out of the provided scala test jar that's prewired in. If I'm not sure how well that'd gell with the built in test runner.

I agree. It'd be great to just override a default arg of something like scala_repositories with a new version/Sha/label or whatever to "bring your own" alt version of the defaults.

Aside. Thank you both for your quick feedback on this. Im trying to help jump start a new team to revamp our bazel setup before I go off on a long sabbaitcal. A parting gift if you will :)

**Comment by ittaiz** [comment] 2018-09-27 04:28
What both @johnynek and I want (but don’t have the time to do) is move all
external dependencies required to be part of specific toolchains so you cN
either declare the default toolchain we build or configure your own with
your own versions.
If you can help with adding a toolchain for scala_test that can be awesome
:)

**Comment by bguthrie** [comment] 2018-10-10 16:39
@johnynek When you suggest "implementing your own," do you mean copying and pasting that method into one's local build and tweaking the relevant library versions? Colleague of @softprops here.

**Comment by johnynek** [comment] 2018-10-10 17:47
yeah....

It's not perfect, but controlling your versions with a .bzl file and function you call is not terrible.

So, you'd put a file in your repo with a copy-paste of that function, then you would tweak the versions as needed.

We use bazel-deps: https://github.com/johnynek/bazel-deps at stripe, so we just use bind to point the version we set up in bazel-deps. That has been easy for us (and we don't actually copy that function into our repo since the version set gets ignored).

**Comment by exchgr** [comment] 2018-10-15 23:01
Hi there, another colleague of @softprops here. 

We've tried setting the version of scalacheck and scalactic back in time to the versions we previously relied on, while using bazel 0.15.2 and rules_scala @ a594886. Right now that change is not ready to submit publicly, although I expect we'll prepare something in the form of a toolchain once we get this all working.

That seems to mostly build (and run tests) alright, except now we're encountering another strange issue with building mixed scala/java sources within the same `scala_library` call. In `bazel-bin/<module>/<module>.jar`, we see `.class` files for the corresponding Scala sources, but not for the corresponding Java sources, even though both scala and java sources are explicitly included in the `srcs` glob. However, we do see all the relevant Java `.class` files in `bazel-bin/<module>/<module>_java-hjar.jar`. Our `scala_library` rule is something like this:

```python
scala_library(
    name = "base",
    srcs = glob(
        [
            "src/main/scala/**/*.scala",
            "src/main/java/**/*.java",
        ],
    ),
    # ...
)
```

In our codebase, there are scala files that depend on java files, and java files that depend on scala files, so creating a separate `scala_library` and `java_library` for each language doesn't seem feasible at this point.

We were also able to reproduce this behavior by observing it in a (non-failing) test from `rules_scala` that I don't recall right now, but we'll follow up with that tomorrow. In bazel 0.6.x, we see the expected mixture of Scala- and Java-based `.class` files in the final `.jar`. I'm wondering if this is intended behavior or a bug.

Either way, how do we include the Java-based `.class` files along with the Scala ones in the final `.jar` file?

**Comment by johnynek** [comment] 2018-10-15 23:37
@exchgr see this comment: https://github.com/bazelbuild/rules_scala/issues/619#issuecomment-424565857

There is no contract that the sources wind up in the same jar. A rule can have multiple outputs.

What is causing a requirement that all sources wind up in the same jar?

The deploy jar target should have that and bazel run should work. Those are the contracts.

**Comment by ittaiz** [comment] 2018-10-16 04:13
Additionally what you can do is have small genrule that takes both jars,
unpacks them and packs them together if it’s a hard requirement (which I
agree with Oscar it shouldn’t be)

**Comment by exchgr** [comment] 2018-10-16 15:35
Thanks for the responses. Sorry if I was unclear. There's no requirement on our part that these classes are in the same jar. But we also aren't seeing the `<module>_java.jar` at this point. Right now, I see these:

- `<module>.jar` - containing only Scala classes
- `<module>_java-hjar.jar` - containing only Java header classes

It doesn't particularly matter where the full Java classes land in the output, but I don't see them at all.

**Comment by ittaiz** [comment] 2018-10-16 16:50
Strange. Can you checkout rules scala and see if you can see the java file
there for any of the targets?

**Comment by exchgr** [comment] 2018-10-17 16:31
It looks like the java jars for the targets in rules_scala tests actually did show up correctly. But I did some digging in our bazel project and found there's something that prevents those java jars from getting built. Somewhere down the line, we're relying on `ctx.files.artifacts` to stage our jars. But that only includes the jars that don't have the `_java` suffix. It relies on the [default outputs](https://docs.bazel.build/versions/master/skylark/rules.html#requesting-output-files). It looks like the default outputs don't include the `_java.jar` files. I'll open a PR with what works for me.

**Comment by exchgr** [comment] 2018-10-17 16:50
Here's a preliminary PR, notably omitting tests https://github.com/bazelbuild/rules_scala/pull/629

**Comment by ittaiz** [comment] 2020-01-17 19:37
Closing this issue since it seems (from skimming the issue) that #631 fixed it.
If this isn't the case please re-open

**Closed by ittaiz** 2020-01-17 19:37 UTC

**Comment by exchgr** [comment] 2020-01-20 16:33
Sounds good, thanks!
